@startuml
title MLD - Pizzas et Ingrédients

entity PIZZA {
    * id : INT <<PK>>
    --
    name : VARCHAR
    imageUrl : VARCHAR
    price : FLOAT
    created_at : DATETIME
    updated_at : DATETIME
}

entity INGREDIENT {
    * id : INT <<PK>>
    --
    name : VARCHAR
    price : FLOAT
    created_at : DATETIME
    updated_at : DATETIME
}

entity PIZZAS_HAS_INGREDIENTS {
    * pizza_id : INT <<PK,FK>>
    * ingredient_id : INT <<PK,FK>>
}

PIZZA ||--o{ PIZZAS_HAS_INGREDIENTS
INGREDIENT ||--o{ PIZZAS_HAS_INGREDIENTS

@enduml